export default {
  Tables: {
    Accounts: 'accounts',
    Announcements: 'announcements',
    Collection: 'collection',
    CollectionXImage: 'collection_x_image',
    Featured: 'featured',
    FeaturedTeaser: 'featured_teaser',
    FeaturedXCollection: 'featured_x_collection',
    Games: 'games',
    Images: 'images',
    ImageXCategory: 'image_x_category',
    Leaderboard: 'leaderboard',
    LeaderboardEntries: 'leaderboard_entries',
    Tags: 'categories',
    Tokens: 'tokens',
    TwitchLivestreams: 'twitch_livestreams',
    UserAvatars: 'user_avatars',
    UserGroups: 'user_groups',
    UserIdentity: 'user_identity',
    Users: 'users',
    UserSettings: 'user_settings',
    UserXGame: 'user_x_game',
    UserXUserGroup: 'user_x_user_group',
  },
}
