#!/bin/sh -eu

cd "$RUN_DIR"

export APP_CONFIG=config.json
nodemon \
  -x "node --experimental-specifier-resolution=node --loader ts-node/esm" \
  -w src/server \
  -w src/common \
  src/server/main.ts
